name: zip_path_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.10+53

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  shared_preferences: ^2.3.3
  path_provider: ^2.1.5
  crypto: ^3.0.6
  file_picker: ^8.1.2
  image: ^4.2.0
  google_sign_in: ^6.2.2
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  cloud_functions: ^5.1.3
  firebase_storage: ^12.3.0
  flutter_cache_manager: ^3.4.1
  in_app_purchase: ^3.2.0
  google_mobile_ads: ^5.2.0
  animate_do: ^4.2.0
  url_launcher: ^6.3.1
  package_info_plus: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/levels/pack_core_v1.json
    - assets/levels/pack_curated_v1.json
    - assets/levels/pack_all_v1.json
    - assets/levels/pack_linkedin_v1.json
    - assets/levels/pack_linkedin_editor_v1.json
    - assets/levels/pack_linkedin_js_generated_v1.json
    - assets/levels/pack_bulk_variant_100_v1.json
    - assets/levels/pack_bulk_variant_200_v1.json
    - assets/levels/pack_variant_alphabet_v1.json
    - assets/levels/pack_variant_alphabet_reverse_v1.json
    - assets/levels/pack_variant_multiples_v1.json
    - assets/levels/pack_variant_roman_v1.json
    - assets/levels/pack_variant_multiples_roman_v1.json
    - assets/levels/master_pack_v1.json
    - assets/levels/pack_world_01_v1.json
    - assets/levels/pack_world_02_v1.json
    - assets/levels/pack_world_03_v1.json
    - assets/levels/pack_world_04_v1.json
    - assets/levels/pack_world_05_v1.json
    - assets/levels/pack_world_06_v1.json
    - assets/levels/pack_world_07_v1.json
    - assets/levels/pack_world_08_v1.json
    - assets/levels/pack_world_09_v1.json
    - assets/levels/pack_world_10_v1.json
    - assets/levels/pack_world_11_v1.json
    - assets/levels/pack_world_12_v1.json
    - assets/levels/pack_world_13_v1.json
    - assets/levels/pack_world_14_v1.json
    - assets/levels/pack_world_15_v1.json
    - assets/levels/pack_world_16_v1.json
    - assets/levels/pack_world_17_v1.json
    - assets/branding/logo_tracePath.png
    - assets/branding/splash_tracePath.png
    - assets/branding/coin_tracepath.png
    - assets/branding/shop_tracepath.png
    - assets/shop/coin_packs/saco_pequeno.webp
    - assets/shop/coin_packs/saco_mediano.webp
    - assets/shop/coin_packs/saco_grande.webp
    - assets/shop/coin_packs/cofre_grande.webp
    - assets/shop/coin_packs/cofre_epico.webp
    - assets/shop/coin_packs/lote_super_epico.webp
    - assets/shop/icons/
    - assets/ui/cards/
    - assets/skins/
    - assets/trails/
    - assets/trails/comic_spiderverse/
    - assets/trails/urban_graffiti/
    - assets/galaxy_trail/
    - assets/vfx/smoke/
